#! /bin/bash
set -exo nounset

# usage: systemctl <server>

[ $# -eq 1 ] || exit 1
T="`sed 's#/$##' <<< "$1"`"

pushd $T
	sudo docker build -t $T .
popd

{
	echo "# This file is automatically generated by: $0 $*"
	sed 's/\$T/'"$T/g" systemctl.in
} | sudo tee /etc/systemd/system/docker-$T.service

sudo systemctl daemon-reload
sudo systemctl enable docker-$T.service
sudo systemctl start  docker-$T.service
sudo systemctl status docker-$T.service

